apiVersion: v1
kind: ConfigMap
metadata:
  name: orflow-config
  namespace: orflow-production
  labels:
    app:         orflow-api
    environment: production
    managed-by:  kubectl
data:
  DB_HOST: "prod-db.orflow.svc.cluster.local"
  ENV: "production"